import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import CardSection from "@/components/CardSection";
import data from "../fakeData.json";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-secondaryWhite min-h-screen">
        <header>
          <nav className="bg-secondaryBlue flex mb-5">
            <h1 className="bg-primaryBlue p-3 px-4 font-semibold">Tasks</h1>
          </nav>
          <Header />
        </header>
        <section className="max-w-7xl w-full mx-auto">
          <CardSection title="pending" cardList={data.cards} />
        </section>
      </main>
    </>
  );
}
